CREATE DATABASE test_db;
\c test_db

CREATE TABLE "fOo" AS SELECT * FROM generate_series(1, 10000000);
ALTER TABLE "fOo" ALTER COLUMN generate_series SET STATISTICS 500;

CREATE UNLOGGED TABLE "bAr" ("bUz" INTEGER);
ALTER TABLE "bAr" ALTER COLUMN "bUz" SET STATISTICS 500;
INSERT INTO "bAr" SELECT * FROM generate_series(1, 1000000);

CREATE TABLE with_oids() WITH OIDS;
