version: "2017-09-20"
allow_concurrent_steps: true

pipeline:

- id: linters
  type: script
  when:
    - event: push
      branch: master
    - event: pull_request
  commands:
  - desc: Set up packages
    cmd: |
      sudo apt-get update
      sudo apt-get install -y python3-pip shellcheck
      sudo pip3 install flake8
  - desc: Run shellcheck
    cmd: find postgres-appliance -name '*.sh' -print0 | xargs -0 shellcheck
  - desc: Run flake8
    cmd: find postgres-appliance -name '*.py' -print0 | xargs -0 python -m flake8

- id: build-spilo-ecr
  env:
    BASE_IMAGE: container-registry.zalando.net/library/ubuntu-22.04
    PGVERSION: 15
    SPILO_TEST_IMAGE: test-spilo-cdp
    MULTI_ARCH_REGISTRY: container-registry-test.zalando.net/acid
  type: script
  when:
    - event: push
      branch: master
    - event: pull_request
  timeout: 10h
  vm_config:
    type: linux
    size: extra_large
  commands:
  - desc: Set up packages
    cmd: |
      sudo apt-get update
      sudo apt-get install -y python3-pip
      sudo pip3 install docker-compose==1.17.1
  - desc: Build test image
    cmd: |
      chmod -R o-w postgres-appliance
      cd postgres-appliance
      docker build --build-arg PGVERSION="$PGVERSION" \
                   --build-arg BASE_IMAGE="$BASE_IMAGE" \
                   -t "$SPILO_TEST_IMAGE" .
      docker images
  - desc: Run general Spilo image tests
    cmd: bash postgres-appliance/tests/test_spilo.sh
  - desc: Test USE_OLD_LOCALES
    cmd: |
      # only on push to the master branch
      if [ -z "$CDP_SOURCE_BRANCH" ]; then
          bash -x postgres-appliance/tests/locales_test/test_locales.sh
      fi
  - desc: Tag and push spilo-cdp docker images
    cmd: |
      # push docker images only for commits to the master branch
      if [ -z "$CDP_SOURCE_BRANCH" ]; then
          cd postgres-appliance

          PATRONIVERSION=$(sed -n 's/^ENV PATRONIVERSION=\([1-9][0-9]*\.[0-9]*\).*$/\1/p' Dockerfile)
          ECR_TEST_IMAGE="$MULTI_ARCH_REGISTRY/spilo-cdp-$PGVERSION:$PATRONIVERSION-p$CDP_TARGET_BRANCH_COUNTER"

          # create a Buildkit builder with CDP specific configuration
          docker buildx create --config /etc/cdp-buildkitd.toml --driver-opt network=host --bootstrap --use

          docker buildx build --platform "linux/amd64,linux/arm64" \
                              --build-arg PGVERSION="$PGVERSION" \
                              --build-arg BASE_IMAGE="$BASE_IMAGE" \
                              -t "$ECR_TEST_IMAGE" \
                              --push .
          cdp-promote-image "$ECR_TEST_IMAGE"
      fi

- id: tag-spilo
  depends_on: [build-spilo-ecr]
  type: script
  requires_human_approval: true
  when:
    event: push
    branch: master
  commands:
  - desc: Tag release spilo image
    cmd: |
      PATRONIVERSION=$(sed -n 's/^ENV PATRONIVERSION=\([1-9][0-9]*\.[0-9]*\).*$/\1/p' postgres-appliance/Dockerfile)
      COUNTER=$(git tag | sed -n "s/^$PATRONIVERSION-p//p" | sort -un | tail -n1)
      TAG="$PATRONIVERSION-p$((COUNTER+1))"

      git gh-tag "$TAG"
