version: "2017-09-20"
pipeline:
- id: build-spilo-cdp
  env: &ENV
    IMAGE: registry-write.opensource.zalan.do/acid/spilo
    PGVERSION: 12
  type: script
  commands:
  - desc: Build and push docker image
    cmd: |
      cd postgres-appliance

      PATRONIVERSION=$(sed -n 's/^ENV PATRONIVERSION=\([1-9][0-9]*\.[1-9][0-9]*\).*$/\1/p' Dockerfile)
      IMAGE="$IMAGE-cdp-$PGVERSION:$PATRONIVERSION-p$CDP_TARGET_BRANCH_COUNTER"

      ./build.sh --build-arg PGVERSION=$PGVERSION --build-arg PGOLDVERSIONS="9.5 9.6 10 11" --build-arg COMPRESS=true -t $IMAGE .

      docker images

      docker push $IMAGE
