version: "2017-09-20"
pipeline:
- id: build-spilo-cdp
  env: &ENV
    IMAGE: registry-write.opensource.zalan.do/acid/spilo
    PGVERSION: 12
  type: script
  commands:
  - desc: Build and push docker image
    cmd: |
      cd postgres-appliance

      COMPRESS=false
      # compress and push docker images only for commits to the master branch
      if [ "x${CDP_SOURCE_BRANCH}" == "x" ] && [ "x${CDP_TARGET_BRANCH}" == "xfeature/pg12" ]; then
          COMPRESS=true
          PATRONIVERSION=$(sed -n 's/^ENV PATRONIVERSION=\([1-9][0-9]*\.[1-9][0-9]*\).*$/\1/p' Dockerfile)
          IMAGE="$IMAGE-cdp-$PGVERSION:$PATRONIVERSION-p$CDP_TARGET_BRANCH_COUNTER"
      fi

      ./build.sh --build-arg PGVERSION=$PGVERSION --build-arg COMPRESS=$COMPRESS -t $IMAGE .

      docker images

      if [ "$COMPRESS" == "true" ]; then docker push $IMAGE; fi
