version: "2017-09-20"
pipeline:
- id: build-spilo-cdp
  env: &ENV
    IMAGE: registry-write.opensource.zalan.do/acid/spilo
    PGVERSION: 13
  type: script
  commands:
  - desc: Build and push docker image
    cmd: |
      cd postgres-appliance

      MASTER=false
      # push docker images only for commits to the master branch
      if [ "x${CDP_SOURCE_BRANCH}" == "x" ] && [ "x${CDP_TARGET_BRANCH}" == "xfeature/pg13" ]; then
          MASTER=true
          PATRONIVERSION=$(sed -n 's/^ENV PATRONIVERSION=\([1-9][0-9]*\.[1-9][0-9]*\).*$/\1/p' Dockerfile)
          IMAGE="$IMAGE-cdp-$PGVERSION:$PATRONIVERSION-p$CDP_TARGET_BRANCH_COUNTER"
      fi

      docker build --build-arg PGVERSION=$PGVERSION -t $IMAGE .

      docker images

      if [ "$MASTER" == "true" ]; then docker push $IMAGE; fi
