version: "2017-09-20"
allow_concurrent_steps: true

pipeline:
- id: push-spilo-ecr
  env:
    BASE_IMAGE: container-registry.zalando.net/library/ubuntu-22.04
    PGVERSION: 16
    MULTI_ARCH_REGISTRY: container-registry-test.zalando.net/acid
  type: script
  requires_human_approval: true
  when:
    - event: push
      branch: master
  timeout: 10h
  vm_config:
    type: linux
    size: extra_large
  commands:
  - desc: Tag and push spilo-cdp image to ecr
    cmd: |
      cd postgres-appliance

      PATRONIVERSION=$(sed -n 's/^ENV PATRONIVERSION=\([1-9][0-9]*\.[0-9]*\).*$/\1/p' Dockerfile)
      ECR_TEST_IMAGE="$MULTI_ARCH_REGISTRY/spilo-cdp-$PGVERSION:$PATRONIVERSION-p$CDP_TARGET_BRANCH_COUNTER"

      # create a Buildkit builder with CDP specific configuration
      docker buildx create --config /etc/cdp-buildkitd.toml --driver-opt network=host --bootstrap --use

      docker buildx build --platform "linux/amd64,linux/arm64" \
                          --build-arg PGVERSION="$PGVERSION" \
                          --build-arg BASE_IMAGE="$BASE_IMAGE" \
                          -t "$ECR_TEST_IMAGE" \
                          --push .
      cdp-promote-image "$ECR_TEST_IMAGE"

- id: tag-spilo
  depends_on: [push-spilo-ecr]
  type: script
  requires_human_approval: true
  when:
    event: push
    branch: master
  commands:
  - desc: Tag release spilo image
    cmd: |
      PATRONIVERSION=$(sed -n 's/^ENV PATRONIVERSION=\([1-9][0-9]*\.[0-9]*\).*$/\1/p' postgres-appliance/Dockerfile)
      COUNTER=$(git tag | sed -n "s/^$PATRONIVERSION-p//p" | sort -un | tail -n1)
      TAG="$PATRONIVERSION-p$((COUNTER+1))"

      git gh-tag "$TAG"
