#!/bin/sh -e

CHPST="chpst -u postgres"
if ! $CHPST true 2> /dev/null; then
    CHPST=""
fi

exec 2>&1
exec $CHPST env -i PGAPPNAME="pgq ticker" SSL_RESTAPI_CERTIFICATE_FILE="$SSL_RESTAPI_CERTIFICATE_FILE" SSL_RESTAPI_PRIVATE_KEY_FILE="$SSL_RESTAPI_PRIVATE_KEY_FILE" SSL_RESTAPI_CA_FILE="$SSL_RESTAPI_CA_FILE" /scripts/patroni_wait.sh --role master -- /usr/bin/pgqd /home/postgres/pgq_ticker.ini
